# Generated by Django 3.0.6 on 2020-07-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='created_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='title',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
