# Generated by Django 3.0.6 on 2020-07-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200714_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
